### PR TITLE
Frontend libs upgrade

### PR DESCRIPTION
**Pull request by bosusites**
Upgrade of frontend libs to the latest versions.

### CODE REVIEW

**Comment by gordon-matt** [comment]
@bosusites Thanks for this. I have noticed an error with one of the plugins though:
image
Please see if you can fix that

**Comment by bosusites** [comment]
@gordon-matt I haven't been able to reproduce the error. Can you please give a step by step to replicate?

**Comment by gordon-matt** [comment]
@bosusites

1. I merged your fork into develop branch
2. Right-clicked libman.json and got latest client side libraries
3. Rebuilt solution
4. Ran solution
5. Cleared browser cache
6. Went to TinyMce page and everything seemed working until I hit F12 to see dev tools
7. CTRL+F5 forced refresh to make sure cache was cleared
8. Same error showing in dev tools.

Note I am using FireFox. Unsure if that makes any difference. I wouldn't think so, but you never know...

**Comment by gordon-matt** [comment]
@bosusites Unsure what was happening yesterday, but the error is not happening today. Obviously something dodgy in my environment.. so don't bother yourself with it any more.

**Pull request merged**
