### PR TITLE
Add "zipdl" command

### PR DESCRIPTION
**Pull request by trannamtrung1st**
Hi @gordon-matt, I create this pull request to solve issue #64. Take a look at it when you have time. Thanks 👍

### CODE REVIEW

**Comment by gordon-matt** [comment]
Thanks. However, I don't see it working. I tried adding "zipdl" to the toolbar in Index.cshtml, but that doesn't show anything. So how did you test your code? Should it be something else instead of "zipdl"? Please add the correct option to the Index.cshtml file, so we can test it.

**Comment by trannamtrung1st** [comment]
Hi @gordon-matt , it is already the working commit. You just have to start it up and select two or more files to download (or download a folder). Then a zip file will be returned instead of separate file like before.

**Comment by gordon-matt** [comment]
I am seeing some very strange behavior. When I download your code directly, it works.. but when I merged and got latest code, the downloading does not work anymore. Hmmm.. I will need more time to figure out why.

**Comment by trannamtrung1st** [comment]
> I am seeing some very strange behavior. When I download your code directly, it works.. but when I merged and got latest code, the downloading does not work anymore. Hmmm.. I will need more time to figure out why.

This pull request will merge into branch **develop**, did you sync it with **master**? Can you describe the behavior clearly so maybe I can help?

**Comment by gordon-matt** [comment]
Yep, of course it's synced and also I was working with the develop branch, my friend.. Haha! Anyway, I tried it again today.. and now it works. That is very strange and I'm not sure what the issue was before.. possibly a caching issue? Anyway, it doesn't matter. It works now. I will look at your other PR before I release a new version.

**Comment by gordon-matt** [comment]
@fsmirne You may want to consider supporting this feature in the Azure driver.

**Pull request merged**
