### PR TITLE
Several Improvements / Bug Fixes

### PR DESCRIPTION
**Pull request by fsmirne**
- Change .net core framework version to 3.1 as it's LTS.
- Replace Json.Net with System.Text.Json.
- Make modifications to allow for new json serializer to work with polymorphic data.
- Fix small bug with AzureStorage Controller
- Improve BaseModel, RootModel and DirectoryModel code.
- Remove unused variable in the BaseModel CreateAsync functions

### CODE REVIEW

**Comment by fsmirne** [comment]
@gordon-matt can you take a look at this. I've been testing elFinder.NetCore with .netcore 3.1 and  there's no easy way to get it to work without the these changes...
Thank you!

**Comment by gordon-matt** [comment]
Hi @fsmirne ,

This is on my list of things to look at. I've been really busy lately.

Are you saying you want it to be purely 3.1 though? What about for people still using .Net Core 2.2? I haven't yet looked at what you've added/changed, but if it's some new feature, how about using the **#If** preprocesor directive to make it for .Net Core 3 only and still continue without that feature for 2.2?

I'll see if I can find some time to look at your changes tomorrow.

**Comment by fsmirne** [comment]
Yes, this uses the new System.Text.Json serializer. It was introduced in version 3. I think going forward, we can support 3.1 as it's LTS. Version 2.2 is end of life now. If people really want to use 2.2, they can stay on the current version, but the best way going forward is to switch to 3.1 as it's the only one being supported by Microsoft. I'll leave it to your discretion though...

**Comment by gordon-matt** [comment]
@fsmirne Your changes are good. All seems to be working fine. I have just uploaded new versions to NuGet. As always, thanks for your contribution.

**Pull request merged**
