### PR TITLE
add support for archive and extract (zip file)

### PR DESCRIPTION
**Pull request by nhuthan**
Add archive and extract commands.
Currently support only zip files (but still does not support on azure storage)

### CODE REVIEW

**Comment by gordon-matt** [comment]
Thanks for this. It looks good, but I will need to test it. One small thing: can you please remove the files in .vscode from the commit? You can add the following to the **.gitignore** file: `.vscode/`

**Review by gordon-matt — APPROVED** [review]

**Comment by gordon-matt** [comment]
@fsmirne Would you like to implement archive and extract functions for Azure before I publish a new version to NuGet?

**Comment by fsmirne** [comment]
@gordon-matt I will check how this was implemented. I'm not sure this will be possible on Azure but I'll let you know

**Comment by fsmirne** [comment]
@gordon-matt I was able to take a look at the library we're using for creating and extracting archives. All the operations are done at the file system level and cannot be done in memory. With this library there's no way to implement that functionality in Azure. We'll have to either look for another library or leave Azure without it...

**Comment by fsmirne** [comment]
@gordon-matt I came up with a workaround. It's not the most efficient way of doing things, but at least it will work. I will create a pull request shortly...
Thanks

**Pull request merged**
