### PR TITLE
Support for API 2.1 + Other bug fixes

### PR DESCRIPTION
**Pull request by fsmirne**
Hey Matt,

I've added support for elFinder API 2.1. In the process, I've refactored a some of the code and put functions in alphabetical order, etc. Both elFinder.NetCore and AzureConnector are updated to the latest version.

I've also fixed a couple of bugs. Please take a look and see if you'd like to merge with your repository and maybe release a new version on Nuget.

Let me know if you have any questions...

### CODE REVIEW

**Comment by gordon-matt** [comment]
Thanks, Flavio. It seems like a lot of this is whitespace changes again, which makes it very difficult for me to review what has actually changed, because there's so much of it. I will start on it soon, but it may take a few days... last time I merged changes too quickly and had bugs because of not doing enough tests - I need to be more careful this time.

**Comment by fsmirne** [comment]
Of course. Do your due diligence. Unfortunately since you're using spaces and I'm using tabs, even copying and pasting sections of the file to put things in alphabetical order causes big changes. Same thing happened with files that were originally created using tabs and then checked in with spaces like files in the AzureStorage project. Maybe we can add the changes in https://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs to help remidiate the situation...
On the other hand, feel free to change anything as you see fit. I'll look for a way to fix this since I do want to keep your repository up to date as I make improvements to keep things sync'ed with the new API. There's no point in continuing with my fork separate as it will not be good for the community...

**Comment by gordon-matt** [comment]
I've made some of the changes. Not done yet though. I'll let you know once it's all merged, tested and released on NuGet.org.

**Comment by gordon-matt** [comment]
OK please have a look at the "develop" branch and test that. One bug I noticed is that any files over about 500kb or so will upload in multiple parts with the name "blob", "blob copy" etc. This is very strange behavior and I assume it's probably elfinder itself doing this and not because of any change you have made. I am guessing it might just be that we need to increase the max upload size in the config.. or it could be a bug that we need to file on the elfinder repo. Have a look though and let me know your thoughts.

**Comment by gordon-matt** [comment]
@fsmirne Please respond to the above comment when you have time. Let's finish this before making any more changes. Thanks.

**Comment by fsmirne** [comment]
I'm looking at it, but there are a lot of changes to review. Some things I had fixed got broken or "unfixed" during the latest commit i.e. delete sound not being found, etc.

It will take ame a few days to get it done.

About the 500k limit, I think this is a new feature of elfinder that breaks large files into parts and I need to see how they are doing it so I can code for it in the backed. Shouldn't be too bad once I figure out the mechanism. I will see if I can fix that as well

**Comment by fsmirne** [comment]
Hey Matt,

I've fixed the chunked uploads bug. Some of the json structure has changed from 2.0 to 2.1 and I've moved those sections to the correct location. Hopefully that's all that's needed for now.
Take a look and let me know if there's anything else you see that doesn't work quite right.
Thanks

**Comment by gordon-matt** [comment]
@fsmirne Hi Flavio. Thanks for the fix. Everything seems to be okay from my side now. Please get latest version of the repo and test it your side. If you think everything is fine, I will upload new NuGet packages.

**Comment by fsmirne** [comment]
Matt, I just grabbed the latest version and tested the 2.1 features. Everything looks good! I say we can release the new version to nuget :)

**Comment by gordon-matt** [comment]
@fsmirne All done. **Note:** Please do one of the following before making any more changes:

1. Either delete your fork and create a new one or...

2. Merge my code and then revert any changes that are still on that fork...

The reason I'm asking this is because any changes left over will just be 95% whitespace differences and a few small changes I rejected. So if you don't revert those changes, then I will keep seeing them again and again with every pull request. Thanks.

**Pull request closed without merging**
