### PR TITLE
Migrate to asp.net 8 core and other libs upgrade

### PR DESCRIPTION
**Pull request by utilsites**
**Migrated to asp.net 8 core, it works well.**
Only problem detected was when debugging the project, after downloading an image the website stops, but this already happens on the .net 3.1 version. Need to investigate more to discover the cause.

### CODE REVIEW

**Comment by utilsites** [comment]
As no feedback was received for some weeks, I'm assuming this repo is discontinued, and I'm going to close this pull request, but can reopen later by request.
Will continue the work on my forke repo https://github.com/utilsites/elFinder.NetCore

**Comment by gordon-matt** [comment]
The repo is most certainly not discontinued. I am somewhat busy at the moment and have yet to take a look at this.

**Comment by utilsites** [comment]
Ok, nice! Hope you can look at it.
I opened a new pull request from other branch, with all the migrations and updates done, including .net 8, elFinder frontend libs and tinyMCE, all to latest versions:
[New Pull Request](https://github.com/gordon-matt/elFinder.NetCore/pull/76)
It works well, hope you can integrate it, and improve something if it's necessary, for now seems all ok.

Just one question, I saw you new CMS project, it seams there is used the PHP ResponsiveFileManager instead of elFinder, can you comment on that please? I was a bit hesitant about this, I'm missing some problem on this project or add to do with missing updates?

**Comment by gordon-matt** [comment]
Thank you for your contributions. I will need time to go through it; I am hoping to find some time this weekend.

It's been a while since I made any changes to this project though. What is your reason for wanting to move directly to ASP.NET 8? As far as I recall, the NuGet package has been working fine with .NET 5, 6, and 7. Is there something in .NET 8 that has changed things so much that has made this PR necessary? I have not yet had the chance to look into .NET 8 myself.

With regards to my CMS project (I have 3 of them actually.. the original was KoreCMS.. targeting MVC5/.NET 4.8, then MantleCMS which is now stable.. and I have a partially implemented one called InfernoCMS which is for Blazor.. but haven't had time to finish it off).

I opted for Responsive File Manager in the CMS projects simply because it looks nicer. elFinder is probably more feature-rich, but it's not as nice-looking. I like them both and use them both for different projects.

**Comment by utilsites** [comment]
Thanks for looking at this.
I was searching for a web file manager for asp.net core, and found this project.
I was also building a new website in asp.net core, so used the latest .net version, and as this project was done in .net 3.1 I though it was old and needed an upgrade, so let's go to the latest version. I Don't like to start new projects with old modules. Also thought that would be good to migrate the frontend with all old client libs, to be sync with the original project that is being maintained, and also the tinyMCE version.

Regarding responsive file manager, thanks for the information. In my case, I also used it in .NET MVC and worked well and also agreed that is nice-looking, but never liked the idea of having the PHP box to run that and have less control and less integration. So, in my case, the elFinder styles, particular with themes is good enough, and like a lot to have it in the same tech stack (asp.net core).

Nice, need to try your CMSs.
Lets collaborate and upgrade this nice project :)

**Comment by gordon-matt** [comment]
@utilsites You're right; it was about time for an update anyway due to the security vulnerabilities.. and I figure anyone needing to run it on .NET 5, 6 or 7 can do so using the older NuGet package.

You're the first person I've heard say they've used ResponsiveFileManager in .NET other than myself. I am curious to know whether you did so by reading my old [CodeProject article](https://www.codeproject.com/Tips/1004596/Using-Responsive-File-Manager-in-ASP-NET-MVC). In any case, the newer one (for .NET Core 3 and up) uses PeachPie (just a NuGet package) instead and you can find the sample project here: [PeachPie Responsive File Manager](https://github.com/gordon-matt/peachpie-responsive-file-manager)

I am more than happy to look at any PRs you want to submit; whether for this, or one of my CMS projects or anything else. I haven't had a lot of time recently for working on my own projects like this, but I believe I can make time for reviewing work done by others - just be sure to keep the PRs relatively small so it's quicker / easier to review. For example, it's preferable to have 5 small PRs than 1 massive one. Of course there are times when it can't be helped if the massive PR is work all done to support one particular feature, for example. But in general, smaller is better.

Thanks and enjoy the rest of your weekend.

**Comment by utilsites** [comment]
Thanks for continuing with the project upgrade.

Yes, I implemented the responsive file manager with the help of your [CodeProject article](https://www.codeproject.com/Tips/1004596/Using-Responsive-File-Manager-in-ASP-NET-MVC) in the past! I had the link saved and confirmed that was that one! Thanks by the way :) I made a donation at least for responsiveFileManager creator. Now I will not use the next version with PeachPie, going to use elFinder!

Thanks for the guidance on pull requests.

**Pull request closed without merging**
