### PR TITLE
Fix hidden thumb directory bug

### PR DESCRIPTION
**Pull request by fsmirne**
Here's the fix for the hidden thumb directory bug

### CODE REVIEW

**Review by gordon-matt — APPROVED** [review]

**Comment by gordon-matt** [comment]
Many thanks for your hard work. I have released the new version on NuGet and there is also the Azure Storage package there as well: https://www.nuget.org/packages/elFinder.NetCore.AzureStorage/. Since I don't have an Azure account, I cannot test that connector and not 100% sure how to set it up as well. It looks like we just set the following in **Startup**:

```
AzureStorageAPI.AccountName = "[Name]";
AzureStorageAPI.AccountKey = "[Key]";
```

and then change the `rootDirectory` in `AzureStorageController.GetConnector()`, right? Could you please add a small section to the README file for that?

**Comment by fsmirne** [comment]
No problem!

Yeah, it's completely transparent. All you need to do is fill out those
values and choose the root directory as the share name in Azure and
everything just magically works.

I will add the notes to the readme explaining the step by step.

BTW, the Web project on my GitHub seems to be more updated than yours. On
yours I was having trouble with the resize window not displaying properly.
On mine that seems to be correct. Maybe there's some CSS conflicts on yours.

In any way, I will fork your project and keep making changes to it. I want
to add the elfinder 2.1 advanced features soon.

Later

**Comment by gordon-matt** [comment]
About the web project, I didn't merge all of your changes because honestly I didn't like that you moved the elfinder and themes locations and removing the `[Route]` attributes, etc. Also I wanted to make some of my own changes as well. It should be easy to now swap connectors by sharing one elFinder options in `/Views/FileManager/Index.cshtml` and just change the URL there. Same for the `/Views/TinyMCE/Browse.cshtml` view as well.. when we get new conenctors, we just add a controller for it (with no views of its own) and then swap the URLs in those 2 pages is enough.

Feel free to make some changes to fix CSS issues or whatever, but for default locations, please leave as-is. Thanks and have a great weekend.

**Comment by fsmirne** [comment]
If you use bower and download the bower packages for elfinder and the
themes that exist there, they will be installed on the lib folder by
default. Also the default routing structure in MVC doesn't require the
[Route] attribute. That's why I had everything like that.

I tried to keep everything as close as possible to the default instead of
customizing things. The views I created were based on the latest elfinder
HTML as well.

I hope this explains my structure choices.

**Comment by gordon-matt** [comment]
About bower, your version was actually missing the `bower.json` and `bower.cc` files and you had checked in all the files under `lib` into source control, which should have been ignored with a `.gitignore` file. So I guess there's a misunderstanding because you did that by accident? Anyway, I will see about adding elFinder and the related themes through bower like you suggested - it's a good idea.

For the `[Route]` attributes, I understand what you are saying, but I still prefer to keep the attributes. Anyone who writes code in .NET Core understands exactly that they can use those or not - it's up to them. If they don't like them, they can remove them.

As for the latest elFinder config, sure.. you can update that if you like. It was just something I missed last time when copying your code to mine.

**Pull request merged**
